# There are 2 defined services apache and nginx.
# I mainly use apache, so I setup the volumes more proper, as it would
# map the local `html` folder to the target container's Apache DocumentRoot.
#
# You could do similar thing for nginx.
version: "3"
services:
  apache:
    image: httpd:2.4.41-alpine
    ports:
      - 5000:80
    volumes:
      - ./html:/usr/local/apache2/htdocs

  nginx:
    image: nginx:1.17.8-alpine
    ports:
      - 4000:80
    volumes:
      - ./html:/usr/share/nginx/html
